### ISSUE TITLE
spring-boot demo url

### ISSUE THREAD

**Issue by kane-xie** [knightliao/disconf-demos-java#2]
你好，我安装了disconf-spring-boot-demo，请问web端口和路径是？我试了localhost:8080和8081都不行

**Comment by knightliao** [comment]
https://github.com/knightliao/disconf-demos-java/blob/master/disconf-spring-boot-demo/disconf-spring-boot-web/src/main/resources/application.properties   server.port=8081 应该是8081，你再试下
