### ISSUE TITLE
在eclipse中启动项目，disconf保错

### ISSUE THREAD

**Issue by szlwin** [knightliao/disconf-demos-java#3]
问题描述：
      在Eclipse，使用maven启动web项目时，其disconf保错，具体信息如下：
      java.lang.IllegalArgumentException: error at ::0 can't find referenced pointcut anyPublicMethod

     但如打包成war包，则可在tomcat中正常启动。
     另如使用STS则可启动成功。
环境信息：
     disconf版本：2.6.32
     xml配置信息：
    
	<bean id="disconfMgrBean" class="com.baidu.disconf.client.DisconfMgrBean"
	      destroy-method="destroy">
	    <property name="scanPackage" value="com.mogoroom"/>
	</bean>
	<bean id="disconfMgrBean2" class="com.baidu.disconf.client.DisconfMgrBeanSecond"
	      init-method="init" destroy-method="destroy">
	</bean>
	
    <bean id="configproperties_no_reloadable_disconf"
      class="com.baidu.disconf.client.addons.properties.ReloadablePropertiesFactoryBean">
	    <property name="locations">
	        <list>
	            <value>classpath:jdbc.properties</value>
	            <value>classpath:systemconfig.properties</value>
	        </list>
	    </property>
	</bean>

	<bean id="propertyConfigurerForProject1"
      class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">
	    <property name="ignoreResourceNotFound" value="true"/>
	    <property name="ignoreUnresolvablePlaceholders" value="true"/>
	    <property name="propertiesArray">
	        <list>
	            <ref bean="configproperties_no_reloadable_disconf"/>
	        </list>
	    </property>
	</bean>

**Comment by knightliao** [comment]
理论上应该是不会报这个错的，你试下最新版的看看？
