### ISSUE TITLE
demo中的disconf.properties文件中文注释乱码呢

### ISSUE THREAD

**Issue by cheart-gh** [knightliao/disconf-demos-java#4]
三个demo中的disconf.properties文件都是，看下呗

**Comment by knightliao** [comment]
也不是乱码，是unicode的问题

![image](https://cloud.githubusercontent.com/assets/3657476/18259963/3af4e248-741c-11e6-9c58-40b96ff4cc33.png)

**Comment by knightliao** [comment]
IDE上是OK的
