### ISSUE TITLE
standalone-demo打可执行jar报错，maven3.0.4，jdk1.8，执行mvn clean package

### ISSUE THREAD

**Issue by lyg123** [knightliao/disconf-demos-java#8]
[ERROR] Failed to execute goal com.github.knightliao.plugin:starter-shade-maven-plugin:1.0.0:shade (default) on project disconf-standalone-demo: Error creating shaded jar: org.sonatype.aether.util.DefaultRepositorySystemSession cannot be cast to org.eclipse.aether.RepositorySystemSession -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.knightliao.plugin:starter-shade-maven-plugin:1.0.0:shade (default) on project disconf-standalone-demo: Error creating shaded jar: org.sonatype.aether.util.DefaultRepositorySystemSession cannot be cast to org.eclipse.aether.RepositorySystemSession
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating shaded jar: org.sonatype.aether.util.DefaultRepositorySystemSession cannot be cast to org.eclipse.aether.RepositorySystemSession
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:546)
	at org.apache.maven.plugins.shade.mojos.StarterShade.execute(StarterShade.java:118)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.ClassCastException: org.sonatype.aether.util.DefaultRepositorySystemSession cannot be cast to org.eclipse.aether.RepositorySystemSession
	at org.apache.maven.shared.dependency.graph.internal.Maven31DependencyGraphBuilder.buildDependencyGraph(Maven31DependencyGraphBuilder.java:99)
	at org.apache.maven.shared.dependency.graph.internal.DefaultDependencyGraphBuilder.buildDependencyGraph(DefaultDependencyGraphBuilder.java:91)
	at org.apache.maven.shared.dependency.graph.internal.DefaultDependencyGraphBuilder.buildDependencyGraph(DefaultDependencyGraphBuilder.java:66)
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.updateExcludesInDeps(ShadeMojo.java:1126)
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.rewriteDependencyReducedPomIfWeHaveReduction(ShadeMojo.java:1053)
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.createDependencyReducedPom(ShadeMojo.java:969)
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:538)
	... 22 more

**Comment by knightliao** [comment]
http://search.maven.org/#search%7Cga%7C1%7Cstarter-shade-maven-plugin 你看你maven是否有下载这个jar包
重新在shell里执行下

**Comment by lyg123** [comment]
maven里面有这个jar的，
![image](https://cloud.githubusercontent.com/assets/17899660/18424741/fe1883de-78e4-11e6-8f87-5a813ddf0e84.png)


我是在window系统下开发的

**Comment by knightliao** [comment]
jdk 1.7试试看？

**Comment by lyg123** [comment]
试过了，一样的错误
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\think>cd F:\GitHub\disconf-demos-java.git\disconf-standalone-demo

C:\Users\think>F:

F:\GitHub\disconf-demos-java.git\disconf-standalone-demo>java -version
java version "1.7.0_55"
Java(TM) SE Runtime Environment (build 1.7.0_55-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.55-b03, mixed mode)

F:\GitHub\disconf-demos-java.git\disconf-standalone-demo>mvn -v
Apache Maven 3.0.4 (r1232337; 2012-01-17 16:44:56+0800)
Maven home: D:\maven3\bin\..
Java version: 1.7.0_55, vendor: Oracle Corporation
Java home: C:\Java64\jdk1.7.0_55\jre
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
F:\GitHub\disconf-demos-java.git\disconf-standalone-demo>mvn clean package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building disconf-standalone-demo 2.0.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ disconf-standalone-d
emo ---
[INFO] Deleting F:\GitHub\disconf-demos-java.git\disconf-standalone-demo\target
[INFO]
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ disconf-st
andalone-demo ---
[debug] execute contextualize
[WARNING] Using platform encoding (GBK actually) to copy filtered resources, i.e
. build is platform dependent!
[INFO] Copying 0 resource
[INFO] Copying 1 resource
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ disconf-stand
alone-demo ---
[WARNING] File encoding has not been set, using platform encoding GBK, i.e. buil
d is platform dependent!
[INFO] Compiling 24 source files to F:\GitHub\disconf-demos-java.git\disconf-sta
ndalone-demo\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ di
sconf-standalone-demo ---
[debug] execute contextualize
[WARNING] Using platform encoding (GBK actually) to copy filtered resources, i.e
. build is platform dependent!
[INFO] skip non existing resourceDirectory F:\GitHub\disconf-demos-java.git\disc
onf-standalone-demo\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ disco
nf-standalone-demo ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ disconf-standalone-d
emo ---
[INFO] No tests to run.
[INFO] Surefire report directory: F:\GitHub\disconf-demos-java.git\disconf-stand
alone-demo\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-jar-plugin:2.3.2:jar (default-jar) @ disconf-standalone-demo --
-
[INFO] Building jar: F:\GitHub\disconf-demos-java.git\disconf-standalone-demo\ta
rget\disconf-standalone-demo.jar
[INFO]
[INFO] >>> starter-shade-maven-plugin:1.0.0:shade (default) @ disconf-standalone
-demo >>>
[INFO]
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ disconf-st
andalone-demo ---
[debug] execute contextualize
[WARNING] Using platform encoding (GBK actually) to copy filtered resources, i.e
. build is platform dependent!
[INFO] Copying 0 resource
[INFO] Copying 1 resource
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ disconf-stand
alone-demo ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ di
sconf-standalone-demo ---
[debug] execute contextualize
[WARNING] Using platform encoding (GBK actually) to copy filtered resources, i.e
. build is platform dependent!
[INFO] skip non existing resourceDirectory F:\GitHub\disconf-demos-java.git\disc
onf-standalone-demo\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ disco
nf-standalone-demo ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ disconf-standalone-d
emo ---
[INFO] No tests to run.
[INFO] Skipping execution of surefire because it has already been run for this c
onfiguration
[INFO]
[INFO] --- maven-jar-plugin:2.3.2:jar (default-jar) @ disconf-standalone-demo --
-
[INFO]
[INFO] <<< starter-shade-maven-plugin:1.0.0:shade (default) @ disconf-standalone
-demo <<<
[INFO]
[INFO] --- starter-shade-maven-plugin:1.0.0:shade (default) @ disconf-standalone
-demo ---
[INFO] MavenProject: com.baidu.disconf:disconf-standalone-demo:2.0.0 @ F:\GitHub
\disconf-demos-java.git\disconf-standalone-demo\pom.xml
[INFO] use default start shell
[INFO] use default stop shell
[INFO] add resource for profile Profile {id: rd, source: pom}
[INFO] add file:[F:\GitHub\disconf-demos-java.git\disconf-standalone-demo\profil
e\rd] as conf
[INFO] add file:[F:\GitHub\disconf-demos-java.git\disconf-standalone-demo\profil
e\rd\disconf.properties] as conf
[INFO] add file:[F:\GitHub\disconf-demos-java.git\disconf-standalone-demo\profil
e\rd\env] as conf
[INFO] add file:[F:\GitHub\disconf-demos-java.git\disconf-standalone-demo\profil
e\rd\logback.xml] as conf
[INFO] Including com.baidu.disconf:disconf-client:jar:2.6.35 in the shaded jar.
[INFO] Including com.baidu.disconf:disconf-core:jar:2.6.35 in the shaded jar.
[INFO] Including org.apache.httpcomponents:httpclient:jar:4.5.1 in the shaded ja
r.
[INFO] Including org.apache.httpcomponents:httpcore:jar:4.4.3 in the shaded jar.

[INFO] Including commons-codec:commons-codec:jar:1.9 in the shaded jar.
[INFO] Including org.apache.zookeeper:zookeeper:jar:3.3.6 in the shaded jar.
[INFO] Including log4j:log4j:jar:1.2.15 in the shaded jar.
[INFO] Including javax.mail:mail:jar:1.4 in the shaded jar.
[INFO] Including javax.activation:activation:jar:1.1 in the shaded jar.
[INFO] Including jline:jline:jar:0.9.94 in the shaded jar.
[INFO] Including com.google.code.gson:gson:jar:2.2.4 in the shaded jar.
[INFO] Including org.apache.commons:commons-lang3:jar:3.4 in the shaded jar.
[INFO] Including org.reflections:reflections:jar:0.9.9-RC1 in the shaded jar.
[INFO] Including org.javassist:javassist:jar:3.16.1-GA in the shaded jar.
[INFO] Including dom4j:dom4j:jar:1.6.1 in the shaded jar.
[INFO] Including xml-apis:xml-apis:jar:1.0.b2 in the shaded jar.
[INFO] Including com.google.guava:guava:jar:19.0-rc2 in the shaded jar.
[INFO] Including org.aspectj:aspectjtools:jar:1.7.4 in the shaded jar.
[INFO] Including commons-io:commons-io:jar:1.4 in the shaded jar.
[INFO] Including commons-lang:commons-lang:jar:2.4 in the shaded jar.
[INFO] Including org.slf4j:slf4j-api:jar:1.7.6 in the shaded jar.
[INFO] Including ch.qos.logback:logback-core:jar:1.0.9 in the shaded jar.
[INFO] Including ch.qos.logback:logback-classic:jar:1.0.9 in the shaded jar.
[INFO] Including redis.clients:jedis:jar:2.1.0 in the shaded jar.
[INFO] Including commons-pool:commons-pool:jar:1.5.5 in the shaded jar.
[INFO] Including org.springframework:spring-context:jar:4.1.7.RELEASE in the sha
ded jar.
[INFO] Including org.springframework:spring-aop:jar:4.1.7.RELEASE in the shaded
jar.
[INFO] Including aopalliance:aopalliance:jar:1.0 in the shaded jar.
[INFO] Including org.springframework:spring-beans:jar:4.1.7.RELEASE in the shade
d jar.
[INFO] Including org.springframework:spring-core:jar:4.1.7.RELEASE in the shaded
 jar.
[INFO] Including commons-logging:commons-logging:jar:1.2 in the shaded jar.
[INFO] Including org.springframework:spring-expression:jar:4.1.7.RELEASE in the
shaded jar.
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing F:\GitHub\disconf-demos-java.git\disconf-standalone-demo\target
\disconf-standalone-demo.jar with F:\GitHub\disconf-demos-java.git\disconf-stand
alone-demo\target\disconf-standalone-demo-2.0.0-shaded.jar
[INFO] Dependency-reduced POM written at: F:\GitHub\disconf-demos-java.git\disco
nf-standalone-demo\dependency-reduced-pom.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.253s
[INFO] Finished at: Mon Sep 12 13:12:43 CST 2016
[INFO] Final Memory: 32M/229M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.knightliao.plugin:starter-shade-maven-
plugin:1.0.0:shade (default) on project disconf-standalone-demo: Error creating
shaded jar: org.sonatype.aether.util.DefaultRepositorySystemSession cannot be ca
st to org.eclipse.aether.RepositorySystemSession -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
F:\GitHub\disconf-demos-java.git\disconf-standalone-demo>

**Comment by knightliao** [comment]
mvn 升级到3.3.9 试试 https://bitbucket.org/sdorra/scm-manager/pull-requests/22/add-mercurial-bookmarks-to-changeset/diff

**Comment by knightliao** [comment]
https://www.sov5.com/search?q=DefaultRepositorySystemSession+cannot+be+ca+st+to+org.eclipse.aether.RepositorySystemSession&re=1

**Comment by lyg123** [comment]
mvn版本太低了改为3.3.9确实好了，谢谢
